// Centralized course data for all store components
export const courses = [
  {
    id: 1,
    title: "Web Development Fundamentals",
    instructor: "Sarah Johnson",
    rating: 4.8,
    enrolledStudents: 1247,
    price: 299,
    originalPrice: 599,
    image: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=400&h=250&fit=crop",
    category: "Programming",
    duration: "8 weeks",
    level: "Beginner",
    description: "Learn HTML, CSS, and JavaScript fundamentals to build responsive websites.",
    link: "/courses/MERN-Stack"
  },
  {
    id: 2,
    title: "Data Science Essentials",
    instructor: "Dr. Michael Chen",
    rating: 4.9,
    enrolledStudents: 2156,
    price: 399,
    originalPrice: 799,
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=250&fit=crop",
    category: "Data Science",
    duration: "12 weeks",
    level: "Intermediate",
    description: "Master Python, statistics, and machine learning algorithms.",
    link: "/courses/data-science-essentials"
  },
  {
    id: 3,
    title: "Digital Marketing Mastery",
    instructor: "Emma Rodriguez",
    rating: 4.7,
    enrolledStudents: 1893,
    price: 249,
    originalPrice: 499,
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=250&fit=crop",
    category: "Marketing",
    duration: "6 weeks",
    level: "Beginner",
    description: "Learn SEO, social media marketing, and content strategy.",
    link: "/courses/digital-marketing-mastery"
  },
  {
    id: 4,
    title: "UI/UX Design Principles",
    instructor: "Alex Thompson",
    rating: 4.8,
    enrolledStudents: 1567,
    price: 349,
    originalPrice: 699,
    image: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400&h=250&fit=crop",
    category: "Design",
    duration: "10 weeks",
    level: "Intermediate",
    description: "Master user interface and user experience design fundamentals.",
    link: "/courses/ui-ux-design-principles"
  },
  {
    id: 5,
    title: "Mobile App Development",
    instructor: "David Kim",
    rating: 4.6,
    enrolledStudents: 1342,
    price: 449,
    originalPrice: 899,
    image: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400&h=250&fit=crop",
    category: "Programming",
    duration: "14 weeks",
    level: "Advanced",
    description: "Build iOS and Android apps using React Native and Flutter.",
    link: "/courses/mobile-app-development"
  },
  {
    id: 6,
    title: "Business Analytics",
    instructor: "Lisa Wang",
    rating: 4.9,
    enrolledStudents: 987,
    price: 299,
    originalPrice: 599,
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=250&fit=crop",
    category: "Business",
    duration: "8 weeks",
    level: "Intermediate",
    description: "Learn to analyze business data and make data-driven decisions.",
    link: "/courses/business-analytics"
  },
  {
    id: 7,
    title: "Cybersecurity Fundamentals",
    instructor: "Robert Martinez",
    rating: 4.7,
    enrolledStudents: 1123,
    price: 399,
    originalPrice: 799,
    image: "https://images.unsplash.com/photo-1563986768609-322da13575f3?w=400&h=250&fit=crop",
    category: "Security",
    duration: "10 weeks",
    level: "Intermediate",
    description: "Understand cybersecurity threats and protection strategies.",
    link: "/courses/cybersecurity-fundamentals"
  },
  {
    id: 8,
    title: "Cloud Computing with AWS",
    instructor: "Jennifer Lee",
    rating: 4.8,
    enrolledStudents: 1456,
    price: 499,
    originalPrice: 999,
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400&h=250&fit=crop",
    category: "Cloud",
    duration: "12 weeks",
    level: "Advanced",
    description: "Master AWS services and cloud infrastructure deployment.",
    link: "/courses/cloud-computing-aws"
  },
  {
    id: 9,
    title: "Graphic Design Masterclass",
    instructor: "Carlos Mendez",
    rating: 4.6,
    enrolledStudents: 876,
    price: 199,
    originalPrice: 399,
    image: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400&h=250&fit=crop",
    category: "Design",
    duration: "6 weeks",
    level: "Beginner",
    description: "Learn Adobe Creative Suite and design principles.",
    link: "/courses/graphic-design-masterclass"
  },
  {
    id: 10,
    title: "Python for Beginners",
    instructor: "Amanda Foster",
    rating: 4.9,
    enrolledStudents: 2341,
    price: 149,
    originalPrice: 299,
    image: "https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=400&h=250&fit=crop",
    category: "Programming",
    duration: "8 weeks",
    level: "Beginner",
    description: "Start your programming journey with Python fundamentals.",
    link: "/courses/python-for-beginners"
  },
  {
    id: 11,
    title: "E-commerce Strategy",
    instructor: "Mark Wilson",
    rating: 4.7,
    enrolledStudents: 654,
    price: 249,
    originalPrice: 499,
    image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=400&h=250&fit=crop",
    category: "Business",
    duration: "6 weeks",
    level: "Intermediate",
    description: "Build and scale successful e-commerce businesses.",
    link: "/courses/ecommerce-strategy"
  },
  {
    id: 12,
    title: "Artificial Intelligence Basics",
    instructor: "Dr. Sophia Park",
    rating: 4.8,
    enrolledStudents: 1789,
    price: 599,
    originalPrice: 1199,
    image: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=400&h=250&fit=crop",
    category: "AI/ML",
    duration: "16 weeks",
    level: "Advanced",
    description: "Introduction to machine learning and neural networks.",
    link: "/courses/artificial-intelligence-basics"
  }
];

export const internships = [
  {
    id: 1,
    title: "Frontend Development Intern",
    company: "TechCorp Solutions",
    duration: "3 months",
    stipend: "₹15,000/month",
    location: "Remote",
    rating: 4.6,
    enrolledStudents: 234,
    image: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=400&h=250&fit=crop",
    description: "Work on real-world projects using React, Vue.js, and modern web technologies.",
    link: "/internships/frontend-development"
  },
  {
    id: 2,
    title: "Data Science Intern",
    company: "Analytics Pro",
    duration: "6 months",
    stipend: "₹25,000/month",
    location: "Hybrid",
    rating: 4.8,
    enrolledStudents: 156,
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=250&fit=crop",
    description: "Analyze large datasets and build predictive models using Python and ML.",
    link: "/internships/data-science"
  },
  {
    id: 3,
    title: "UI/UX Design Intern",
    company: "Creative Studios",
    duration: "4 months",
    stipend: "₹18,000/month",
    location: "On-site",
    rating: 4.5,
    enrolledStudents: 89,
    image: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400&h=250&fit=crop",
    description: "Design user interfaces and conduct user research for mobile apps.",
    link: "/internships/ui-ux-design"
  },
  {
    id: 4,
    title: "Digital Marketing Intern",
    company: "Growth Marketing",
    duration: "3 months",
    stipend: "₹12,000/month",
    location: "Remote",
    rating: 4.4,
    enrolledStudents: 312,
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=250&fit=crop",
    description: "Manage social media campaigns and SEO strategies for clients.",
    link: "/internships/digital-marketing"
  },
  {
    id: 5,
    title: "Backend Development Intern",
    company: "ServerTech",
    duration: "5 months",
    stipend: "₹20,000/month",
    location: "Hybrid",
    rating: 4.7,
    enrolledStudents: 178,
    image: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400&h=250&fit=crop",
    description: "Develop APIs and database systems using Node.js and MongoDB.",
    link: "/internships/backend-development"
  },
  {
    id: 6,
    title: "Cybersecurity Intern",
    company: "SecureNet",
    duration: "4 months",
    stipend: "₹22,000/month",
    location: "On-site",
    rating: 4.6,
    enrolledStudents: 67,
    image: "https://images.unsplash.com/photo-1563986768609-322da13575f3?w=400&h=250&fit=crop",
    description: "Learn penetration testing and security assessment techniques.",
    link: "/internships/cybersecurity"
  },
  {
    id: 7,
    title: "Cloud Computing Intern",
    company: "CloudWorks",
    duration: "6 months",
    stipend: "₹28,000/month",
    location: "Remote",
    rating: 4.8,
    enrolledStudents: 134,
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400&h=250&fit=crop",
    description: "Work with AWS, Azure, and Google Cloud platforms.",
    link: "/internships/cloud-computing"
  },
  {
    id: 8,
    title: "Mobile App Intern",
    company: "AppStudio",
    duration: "4 months",
    stipend: "₹16,000/month",
    location: "Hybrid",
    rating: 4.5,
    enrolledStudents: 145,
    image: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400&h=250&fit=crop",
    description: "Develop iOS and Android applications using React Native.",
    link: "/internships/mobile-app-development"
  }
];

export const sbpls = [
  {
    id: 1,
    title: "E-commerce Website",
    category: "Web Development",
    duration: "4 weeks",
    price: 199,
    originalPrice: 399,
    rating: 4.7,
    enrolledStudents: 456,
    image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=400&h=250&fit=crop",
    description: "Build a complete e-commerce website with payment integration.",
    link: "/sbpls/ecommerce-website"
  },
  {
    id: 2,
    title: "Machine Learning Model",
    category: "Data Science",
    duration: "6 weeks",
    price: 299,
    originalPrice: 599,
    rating: 4.8,
    enrolledStudents: 234,
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=250&fit=crop",
    description: "Create a predictive model for real-world data analysis.",
    link: "/sbpls/machine-learning-model"
  },
  {
    id: 3,
    title: "Mobile App Development",
    category: "App Development",
    duration: "8 weeks",
    price: 349,
    originalPrice: 699,
    rating: 4.6,
    enrolledStudents: 189,
    image: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400&h=250&fit=crop",
    description: "Develop a full-featured mobile application from scratch.",
    link: "/sbpls/mobile-app-development"
  },
  {
    id: 4,
    title: "Digital Marketing Campaign",
    category: "Marketing",
    duration: "3 weeks",
    price: 149,
    originalPrice: 299,
    rating: 4.5,
    enrolledStudents: 567,
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=250&fit=crop",
    description: "Plan and execute a complete digital marketing strategy.",
    link: "/sbpls/digital-marketing-campaign"
  },
  {
    id: 5,
    title: "UI/UX Design System",
    category: "Design",
    duration: "5 weeks",
    price: 249,
    originalPrice: 499,
    rating: 4.7,
    enrolledStudents: 234,
    image: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400&h=250&fit=crop",
    description: "Create a comprehensive design system for web applications.",
    link: "/sbpls/ui-ux-design-system"
  },
  {
    id: 6,
    title: "Cybersecurity Assessment",
    category: "Security",
    duration: "4 weeks",
    price: 199,
    originalPrice: 399,
    rating: 4.6,
    enrolledStudents: 123,
    image: "https://images.unsplash.com/photo-1563986768609-322da13575f3?w=400&h=250&fit=crop",
    description: "Conduct security audits and vulnerability assessments.",
    link: "/sbpls/cybersecurity-assessment"
  },
  {
    id: 7,
    title: "Cloud Infrastructure",
    category: "Cloud Computing",
    duration: "6 weeks",
    price: 299,
    originalPrice: 599,
    rating: 4.8,
    enrolledStudents: 178,
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400&h=250&fit=crop",
    description: "Design and deploy scalable cloud infrastructure solutions.",
    link: "/sbpls/cloud-infrastructure"
  },
  {
    id: 8,
    title: "Business Analytics Dashboard",
    category: "Business Intelligence",
    duration: "4 weeks",
    price: 179,
    originalPrice: 359,
    rating: 4.5,
    enrolledStudents: 345,
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=250&fit=crop",
    description: "Create interactive dashboards for business data visualization.",
    link: "/sbpls/business-analytics-dashboard"
  }
];

export const memberships = [
  {
    id: 1,
    title: "Starter Plan",
    price: 999,
    originalPrice: 1999,
    duration: "3 months",
    features: [
      "Access to 50+ courses",
      "Basic project support",
      "Community forum access",
      "Certificate of completion",
      "Mobile app access"
    ],
    popular: false,
    link: "/memberships/starter-plan"
  },
  {
    id: 2,
    title: "Professional Plan",
    price: 1999,
    originalPrice: 3999,
    duration: "6 months",
    features: [
      "Access to 100+ courses",
      "Priority project support",
      "1-on-1 mentoring sessions",
      "Advanced certifications",
      "Exclusive workshops",
      "Job placement assistance"
    ],
    popular: true,
    link: "/memberships/professional-plan"
  },
  {
    id: 3,
    title: "Enterprise Plan",
    price: 3999,
    originalPrice: 7999,
    duration: "12 months",
    features: [
      "Access to all courses",
      "24/7 project support",
      "Personal career coach",
      "Industry certifications",
      "Live masterclasses",
      "Internship opportunities",
      "Resume building services"
    ],
    popular: false,
    link: "/memberships/enterprise-plan"
  }
]; 