const courseData = {
  internships: [
    {
      id: 'intern1',
      title: 'Salty Internship',
      image: 'https://res.cloudinary.com/dpstp4ovd/image/upload/v1752141392/Salty_ppt_SkilliZee_Internship_1_z4lbhp.jpg',
      price: 2999,
      rating: 4.8,
      studentsEnrolled: 5200,
      link: 'https://login.skillizee.io/courses/SALTYCO---Internship-for-school-students--6868db3ecf70c7310edcaee2',
      gradeGroup: '7-12',
    },
    {
      id: 'intern1',
      title: 'Salty Internship',
      image: 'https://res.cloudinary.com/dpstp4ovd/image/upload/v1752141392/Salty_ppt_SkilliZee_Internship_1_z4lbhp.jpg',
      price: 2999,
      rating: 4.8,
      studentsEnrolled: 5200,
      link: 'https://login.skillizee.io/courses/SALTYCO---Internship-for-school-students--6868db3ecf70c7310edcaee2',
      gradeGroup: '7-12',
    },
    {
      id: 'intern1',
      title: 'Salty Internship',
      image: 'https://res.cloudinary.com/dpstp4ovd/image/upload/v1752141392/Salty_ppt_SkilliZee_Internship_1_z4lbhp.jpg',
      price: 2999,
      rating: 4.8,
      studentsEnrolled: 5200,
      link: 'https://login.skillizee.io/courses/SALTYCO---Internship-for-school-students--6868db3ecf70c7310edcaee2',
      gradeGroup: '7-12',
    },
  ],
  shortCourses: [
    {
      id: 'intern1',
      title: 'Salty Internship',
      image: 'https://res.cloudinary.com/dpstp4ovd/image/upload/v1752141392/Salty_ppt_SkilliZee_Internship_1_z4lbhp.jpg',
      price: 2999,
      rating: 4.8,
      studentsEnrolled: 5200,
      link: 'https://login.skillizee.io/courses/SALTYCO---Internship-for-school-students--6868db3ecf70c7310edcaee2',
      gradeGroup: '7-12',
    },
    {
      id: 'intern1',
      title: 'Salty Internship',
      image: 'https://res.cloudinary.com/dpstp4ovd/image/upload/v1752141392/Salty_ppt_SkilliZee_Internship_1_z4lbhp.jpg',
      price: 2999,
      rating: 4.8,
      studentsEnrolled: 5200,
      link: 'https://login.skillizee.io/courses/SALTYCO---Internship-for-school-students--6868db3ecf70c7310edcaee2',
      gradeGroup: '7-12',
    },
    {
      id: 'intern1',
      title: 'Salty Internship',
      image: 'https://res.cloudinary.com/dpstp4ovd/image/upload/v1752141392/Salty_ppt_SkilliZee_Internship_1_z4lbhp.jpg',
      price: 2999,
      rating: 4.8,
      studentsEnrolled: 5200,
      link: 'https://login.skillizee.io/courses/SALTYCO---Internship-for-school-students--6868db3ecf70c7310edcaee2',
      gradeGroup: '7-12',
    },
  ],
  sbpls: [
    {
      id: 'intern1',
      title: 'Salty Internship',
      image: 'https://res.cloudinary.com/dpstp4ovd/image/upload/v1752141392/Salty_ppt_SkilliZee_Internship_1_z4lbhp.jpg',
      price: 2999,
      rating: 4.8,
      studentsEnrolled: 5200,
      link: 'https://login.skillizee.io/courses/SALTYCO---Internship-for-school-students--6868db3ecf70c7310edcaee2',
      gradeGroup: '7-12',
    },
    {
      id: 'intern1',
      title: 'Salty Internship',
      image: 'https://res.cloudinary.com/dpstp4ovd/image/upload/v1752141392/Salty_ppt_SkilliZee_Internship_1_z4lbhp.jpg',
      price: 2999,
      rating: 4.8,
      studentsEnrolled: 5200,
      link: 'https://login.skillizee.io/courses/SALTYCO---Internship-for-school-students--6868db3ecf70c7310edcaee2',
      gradeGroup: '7-12',
    },
    {
      id: 'intern1',
      title: 'Salty Internship',
      image: 'https://res.cloudinary.com/dpstp4ovd/image/upload/v1752141392/Salty_ppt_SkilliZee_Internship_1_z4lbhp.jpg',
      price: 2999,
      rating: 4.8,
      studentsEnrolled: 5200,
      link: 'https://login.skillizee.io/courses/SALTYCO---Internship-for-school-students--6868db3ecf70c7310edcaee2',
      gradeGroup: '7-12',
    },
  ],
  caseStudies: [
    {
      id: 'intern1',
      title: 'Salty Internship',
      image: 'https://res.cloudinary.com/dpstp4ovd/image/upload/v1752141392/Salty_ppt_SkilliZee_Internship_1_z4lbhp.jpg',
      price: 2999,
      rating: 4.8,
      studentsEnrolled: 5200,
      link: 'https://login.skillizee.io/courses/SALTYCO---Internship-for-school-students--6868db3ecf70c7310edcaee2',
      gradeGroup: '7-12',
    },
    {
      id: 'intern1',
      title: 'Salty Internship',
      image: 'https://res.cloudinary.com/dpstp4ovd/image/upload/v1752141392/Salty_ppt_SkilliZee_Internship_1_z4lbhp.jpg',
      price: 2999,
      rating: 4.8,
      studentsEnrolled: 5200,
      link: 'https://login.skillizee.io/courses/SALTYCO---Internship-for-school-students--6868db3ecf70c7310edcaee2',
      gradeGroup: '7-12',
    },
    {
      id: 'intern1',
      title: 'Salty Internship',
      image: 'https://res.cloudinary.com/dpstp4ovd/image/upload/v1752141392/Salty_ppt_SkilliZee_Internship_1_z4lbhp.jpg',
      price: 2999,
      rating: 4.8,
      studentsEnrolled: 5200,
      link: 'https://login.skillizee.io/courses/SALTYCO---Internship-for-school-students--6868db3ecf70c7310edcaee2',
      gradeGroup: '7-12',
    },
  ],
  packages: [
    {
      id: 'pack1',
      title: 'Tech Explorer Pack',
      image: 'https://via.placeholder.com/300x180?text=Tech+Explorer+Pack',
      price: 449,
      rating: 4.8,
      studentsEnrolled: 5200,
      link: '#',
      gradeGroup: '7-12',
    },
    {
      id: 'pack2',
      title: 'Creative Genius Bundle',
      image: 'https://via.placeholder.com/300x180?text=Creative+Genius',
      price: 399,
      rating: 4.9,
      studentsEnrolled: 4600,
      link: '#',
      gradeGroup: '4-6',
    },
  ],
  memberships: [
    {
      id: 'mem1',
      title: 'Annual Membership',
      image: 'https://via.placeholder.com/300x180?text=Annual+Membership',
      price: 999,
      originalPrice: 1999,
      duration: '12 Months',
      features: ['Access to all courses', '1:1 Mentorship', 'Exclusive webinars', 'Career counseling', 'Certificate'],
      rating: 4.9,
      studentsEnrolled: 8000,
      link: '#',
      gradeGroup: 'all',
      popular: true,
    },
    {
      id: 'mem2',
      title: 'Monthly Membership',
      image: 'https://via.placeholder.com/300x180?text=Monthly+Membership',
      price: 199,
      originalPrice: 399,
      duration: '1 Month',
      features: ['Access to all courses', 'Community support'],
      rating: 4.7,
      studentsEnrolled: 2000,
      link: '#',
      gradeGroup: 'all',
      popular: false,
    },
  ],
};

export default courseData; 