// Centralized course data for all sections
// To add or update a course, edit this file only

export const courses = [
  {
    id: 'course-ai-beginners',
    section: 'courses',
    title: 'AI for Beginners',
    description: 'Start your journey into Artificial Intelligence.',
    image: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=400&q=80',
    price: 1499,
    rating: 4.8,
    totalEnrolled: 1200,
    link: '/enroll/ai-for-beginners',
  },
  {
    id: 'course-web-dev',
    section: 'courses',
    title: 'Web Development Bootcamp',
    description: 'Build modern websites from scratch.',
    image: 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&w=400&q=80',
    price: 1299,
    rating: 4.7,
    totalEnrolled: 950,
    link: '/enroll/web-development-bootcamp',
  },
  {
    id: 'course-creative-animation',
    section: 'courses',
    title: 'Creative Animation',
    description: 'Unleash your creativity with animation.',
    image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=400&q=80',
    price: 999,
    rating: 4.9,
    totalEnrolled: 800,
    link: '/enroll/creative-animation',
  },
  {
    id: 'course-data-science',
    section: 'courses',
    title: 'Data Science Essentials',
    description: 'Learn the basics of data science and analytics.',
    image: 'https://images.unsplash.com/photo-1513258496099-48168024aec0?auto=format&fit=crop&w=400&q=80',
    price: 1599,
    rating: 4.6,
    totalEnrolled: 1100,
    link: '/enroll/data-science-essentials',
  },
  {
    id: 'course-robotics',
    section: 'courses',
    title: 'Robotics for Kids',
    description: 'Build and program your own robots.',
    image: 'https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=400&q=80',
    price: 1399,
    rating: 4.8,
    totalEnrolled: 900,
    link: '/enroll/robotics-for-kids',
  },
  {
    id: 'course-math-mastery',
    section: 'courses',
    title: 'Math Mastery',
    description: 'Master math concepts with fun challenges.',
    image: 'https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=400&q=80',
    price: 899,
    rating: 4.7,
    totalEnrolled: 1000,
    link: '/enroll/math-mastery',
  },
  // Internships
  {
    id: 'internship-data-analyst',
    section: 'internships',
    title: 'Data Analyst Internship',
    description: 'Analyze real datasets and present insights.',
    image: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=400&q=80',
    price: 2499,
    rating: 4.9,
    totalEnrolled: 300,
    link: '/enroll/data-analyst-internship',
    company: 'Google',
  },
  {
    id: 'internship-web-dev',
    section: 'internships',
    title: 'Web Developer Internship',
    description: 'Build and deploy web apps for real clients.',
    image: 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&w=400&q=80',
    price: 2299,
    rating: 4.8,
    totalEnrolled: 250,
    link: '/enroll/web-developer-internship',
    company: 'Amazon',
  },
  {
    id: 'internship-ai-research',
    section: 'internships',
    title: 'AI Research Internship',
    description: 'Explore artificial intelligence and machine learning.',
    image: 'https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=400&q=80',
    price: 2699,
    rating: 4.7,
    totalEnrolled: 180,
    link: '/enroll/ai-research-internship',
    company: 'OpenAI',
  },
  {
    id: 'internship-game-dev',
    section: 'internships',
    title: 'Game Developer Internship',
    description: 'Create your own games and learn game design.',
    image: 'https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=400&q=80',
    price: 2599,
    rating: 4.8,
    totalEnrolled: 200,
    link: '/enroll/game-developer-internship',
    company: 'Unity',
  },
  {
    id: 'internship-digital-artist',
    section: 'internships',
    title: 'Digital Artist Internship',
    description: 'Create stunning digital art and animations.',
    image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=400&q=80',
    price: 2199,
    rating: 4.9,
    totalEnrolled: 150,
    link: '/enroll/digital-artist-internship',
    company: 'Adobe',
  },
  {
    id: 'internship-eco-innovator',
    section: 'internships',
    title: 'Eco Innovator Internship',
    description: 'Develop solutions for environmental challenges.',
    image: 'https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=400&q=80',
    price: 2399,
    rating: 4.7,
    totalEnrolled: 170,
    link: '/enroll/eco-innovator-internship',
    company: 'WWF',
  },
  // SPBLs
  {
    id: 'spbl-startup-pitch',
    section: 'spbls',
    title: 'Startup Pitch Challenge',
    description: 'Develop and pitch your own business idea.',
    image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=400&q=80',
    price: 1799,
    rating: 4.8,
    totalEnrolled: 400,
    link: '/enroll/startup-pitch-challenge',
  },
  {
    id: 'spbl-eco-warriors',
    section: 'spbls',
    title: 'Eco Warriors Project',
    description: 'Create a plan to save the environment.',
    image: 'https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=400&q=80',
    price: 1699,
    rating: 4.7,
    totalEnrolled: 350,
    link: '/enroll/eco-warriors-project',
  },
  {
    id: 'spbl-community-helper',
    section: 'spbls',
    title: 'Community Helper',
    description: 'Design a campaign to help your neighborhood.',
    image: 'https://images.unsplash.com/photo-1513258496099-48168024aec0?auto=format&fit=crop&w=400&q=80',
    price: 1599,
    rating: 4.9,
    totalEnrolled: 300,
    link: '/enroll/community-helper',
  },
  {
    id: 'spbl-tech-for-good',
    section: 'spbls',
    title: 'Tech for Good',
    description: 'Use technology to solve real-world problems.',
    image: 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&w=400&q=80',
    price: 1899,
    rating: 4.8,
    totalEnrolled: 320,
    link: '/enroll/tech-for-good',
  },
  {
    id: 'spbl-kindness-campaign',
    section: 'spbls',
    title: 'Kindness Campaign',
    description: 'Spread kindness in your school and community.',
    image: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=400&q=80',
    price: 1499,
    rating: 4.7,
    totalEnrolled: 280,
    link: '/enroll/kindness-campaign',
  },
  {
    id: 'spbl-app-design',
    section: 'spbls',
    title: 'App Design Studio',
    description: 'Design and prototype your own mobile app.',
    image: 'https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=400&q=80',
    price: 1999,
    rating: 4.9,
    totalEnrolled: 360,
    link: '/enroll/app-design-studio',
  },
]; 